create table books2(
ID INTEGER PRIMARY KEY IDENTITY(1,1),
AUTHOR VARCHAR(50),
TITLE VARCHAR(50) ,
WORDS INTEGER)

INSERT INTO books2 VALUES('J.K. ROWLING','HARRY POTTER AND THE PHILOSOPHERS STONE',79944)
INSERT INTO BOOKS2 VALUES('J.K. ROWLING','HARRY POTTER AND THE CHAMBER OF SECRETS',85141)
INSERT INTO books2 VALUES('J.K. ROWLING','HARRY POTTER AND THE PRISIONER OF AZKAPAN',107253)
INSERT INTO BOOKS2 VALUES('J.K. ROWLING','HARRY POTTER AND THE GLOBET OF FIRE',190637)
INSERT INTO books2 VALUES('J.K. ROWLING','HARRY POTTER AND  THE ORDEROF THE PHOENIX',257045)
INSERT INTO BOOKS2 VALUES('J.K. ROWLING','HARRY POTTER AND THE HALF-BLOOD PRINCE',168923)
INSERT INTO books2 VALUES('J.K. ROWLING','HARRY POTTER AND THE DEATHLY HALLOWS',197651)

INSERT INTO books2 VALUES('STEPHENIE MEYER','TWILIGHT',118501)
INSERT INTO books2 VALUES('STEPHENIE MEYER','NEW MOON',132807)
INSERT INTO books2 VALUES('STEPHENIE MEYER','ECLIPSE',147930)
INSERT INTO books2 VALUES('STEPHENIE MEYER','BREAKING DAWN',118501)
INSERT INTO books2 VALUES('STEPHENIE MEYER','TWILIGHT',192196)

INSERT INTO books2 VALUES('J.R.R. TOLKIEN','THE HOBBIT',95022)
INSERT INTO books2 VALUES('J.R.R. TOLKIEN','FELLOWSHIP OF THE RING',177227)
INSERT INTO books2 VALUES('J.R.R. TOLKIEN','TWO TOWERS',143436)
INSERT INTO books2 VALUES('J.R.R. TOLKIEN','RETURN OF THE KING',134462)


SELECT AUTHOR, SUM(WORDS) AS PALABRAS_TOTAL_POR_AUTOR FROM BOOKS2 GROUP BY AUTHOR


--USO DE HAVING, ES PARA PONER UNA CONDICION EN LAS AGRUPACIONES EN VEZ DEL WHERE
SELECT AUTHOR, SUM(WORDS )  AS PALABRAS_TOTAL_POR_AUTOR  FROM BOOKS2 GROUP BY AUTHOR HAVING SUM(WORDS)>1000000

--PROMEDIO PALABRAS POR AUTOR
SELECT AUTHOR,AVG(WORDS) AS PROMEDIO_PALABRAS_POR_AUTOR FROM BOOKS2 GROUP BY AUTHOR HAVING AVG(WORDS)=140000
