drop table GROCERIES

CREATE TABLE GROCERIES (
ID INTEGER PRIMARY KEY identity(50,1),
NAME VARCHAR(30),QUANTITY INTEGER,AISLE integer,UNIT_PRICE real)


INSERT INTO GROCERIES values('BANANAS',4,1,1.50)
INSERT INTO GROCERIES values('PEANUT',1,2,15.0)
INSERT INTO GROCERIES values('DARK CHOCOLATE BARS',2,2,10.50)
INSERT INTO GROCERIES values('FRUIT BARS',10,1,34)
INSERT INTO GROCERIES values('PISTACHOS',4,2,51.50)
INSERT INTO GROCERIES values('PISTACHES',5,5,100)
INSERT INTO GROCERIES values('PULPARINDOS',10,6,5.50)



SELECT* FROM GROCERIES
SELECT NAME,QUANTITY FROM GROCERIES ORDER BY NAME asc
select * from GROCERIES order by QUANTITY asc

select * from GROCERIES where AISLE>3	ORDER BY AISLE

SELECT NAME,QUANTITY*UNIT_PRICE AS TOTAL FROM GROCERIES ORDER BY TOTAL DESC

/*MUESTRA TODOS LOS PRODUCTOS QUE SE ENCUENTREN EN EL PASILLO 2*/
select * from GROCERIES where AISLE=2

/*MUESTRA TODOS LOS PRODUCTOS EXCEPTOS LOS QUE SE ENCUENTREN EN EL PASILLO 2 Y LOS ORDENA POR EL NOMBRE*/
SELECT *FROM GROCERIES WHERE AISLE!=2 ORDER BY NAME

/*FUNCION DE SEGREGACION SUM (SUMA TODOS LOS PRECIOS)*/
select SUM(quantity) AS total_precios from GROCERIES

/*FUNCION AVERAGE (PROMEDIO)*/
select AVG (QUANTITY*UNIT_PRICE) from GROCERIES where AISLE=2

/*funcion coun*/
select aisle, COUNT(*) as catidad from GROCERIES group by aisle

/*AGRUPACION*/
SELECT aisle,SUM(quantity) as cantidad from GROCERIES group by AISLE

